version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: friday
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
    day: friday
