name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    name: Release
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Checkout
      uses: actions/checkout@v2

    - name: Get Changelog Entry
      id: changelog_reader
      uses: mindsers/changelog-reader-action@v1.1.0
      with:
        version: ${{ github.ref }}
        path: ./CHANGELOG.md

    - name: Safe Changelog Text
      run: |
          echo '${{ steps.changelog_reader.outputs.log_entry }}' >> $HOME/changelog_entry
          echo "::set-env name=clfile::${HOME}/changelog_entry"
          
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
         login-server: 'docker.pkg.github.com'
         username: ${{ github.repository_owner }} 
         password: ${{ secrets.GITHUB_TOKEN }}

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
          version: latest
          args: --release-notes ${{ env.clfile }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

